### ISSUE TITLE
Deprecated selector in `language-awk/index.less`

### ISSUE THREAD

**Issue by robertobermudez** [c-steiner/language-awk#10]
In `language-awk/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .meta.debug` => `atom-text-editor.editor .syntax--meta.syntax--debug`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by c-steiner** [comment]
Should be fixed with v0.1.12
