### ISSUE TITLE
Closing bracket for the #action patterns does not need to be at beginning of line

### ISSUE THREAD

**Issue by bertysentry** [c-steiner/language-awk#11]
In the `'action'` pattern, the `end` pattern is set to `'^\}'`, which therefore requires the closing bracket to be at the beginning of the line.

However, the below is a perfectly valid awk statement:
```
BEGIN { init = ""; }
```

The problem in this case is that the `'action'` pattern never "ends". It's not visible as it includes `'$self'`, but it kind of loops recursively on itself. Each action will therefore be part of the previous action, recursively.

Another consequence is that the patterns from `source.awk` cannot be included into another language that embeds some awk code, because the never ending pattern prevents the proper closure of the _awk_ section.

Recommended fix: remove entirely the `'action'` pattern, which doesn't add much to the language grammar, except for the `'entity.name.action.awk'` scope. *OR* change the `end` pattern to be simply `'\}'`, but this may not cover brackets into brackets case...

Thank you!

**Comment by bertysentry** [comment]
If you let me commit to your repo, I'll be happy to fix this. Otherwise, I'll just fork it...

**Comment by bertysentry** [comment]
So, I created the pull request to fix the problem.
Thank you! :-)

**Comment by bertysentry** [comment]
thanks for merging! :-) I'll close the issue.

**Comment by c-steiner** [comment]
Hi Bertrand,

Thank you for your contribution. I'll create a new package.
I just want to ask if you're interested in taking complete maintenance of this extension?

The thing is I am no longer using Atom for my daily business and therefore I couldn't spend as much time as I like on this. I'm not sure if this is possible but it would be ok for me if you take the ownership. So if you're interested I give me a note.

**Comment by bertysentry** [comment]
Hi Chris,

Thank you for trusting me to take care of your Atom package! :-)

I'd happily maintain it (and I see there isn't much maintenance to be done, as it's already in a very good shape).

IIRC, you can transfer the ownership of a repository in the [Settings] of the repository, scroll down to the bottom, in the "Danger Zone", you can transfer ownership.

I'll then have to update the Atom package so that it points to the right GitHub repository.

Note: You may want to transfer the ownership of autocomplete-awk as well, I guess...

-- Bertrand
