### ISSUE TITLE
No syntax for function declarations

### ISSUE THREAD

**Issue by ghost** [c-steiner/language-awk#3]
The `function` keyword should be recognized and have a distinct color.

``` awk
function read (file) {
  while (getline l < (path"/"file)) {
    print l
  }
  close(path"/"file)
}
```

Maybe adding `function` to `language-awk/grammars/awk.cson`?

**Comment by c-steiner** [comment]
`function` is already matched but doesn't work if you have a blank between function name and parameter brackets.

```
function foo(bar) {
    # do something
}
```

Should be matched correctly.  
I will take a look on this.

**Comment by ghost** [comment]
You are right, thanks!

``` awk
function foo(bar) {
    # do something
}
```

**Comment by c-steiner** [comment]
With latest version both variants work.

Thanks for the advice.

**Comment by ghost** [comment]
Thank you for putting this up!
