### ISSUE TITLE
Long one liner breaks syntax

### ISSUE THREAD

**Issue by ghost** [c-steiner/language-awk#6]
I do not endorse this form of programming, but found the following syntax broken in Atom.

``` awk
function add(k,v)   { if (seen[k v]++) return; print k (v ? " "v : "") }
```

![x](https://cloud.githubusercontent.com/assets/8317250/11754572/7eb17160-a08f-11e5-813b-ee9fc811bdcc.png)

**Comment by ghost** [comment]
@c-steiner Chris, I don't feel very helpful just reporting bugs. Do you have any tips on how to work on the grammar file?

**Comment by c-steiner** [comment]
@bucaran what do you mean?

If you want to make changes just fork this repository and if you're done create a pull request.

A documentation how grammar definitions work in general can be found here [Language Grammars](https://manual.macromates.com/en/language_grammars). It is from Textmate but Atom uses the same principles.

From my experience: look at the code of other Atom grammars. That's how I get into this. ;-)

And at last: reporting a bug and providing examples or screenshots is very helpful.

**Comment by ghost** [comment]
That link should be helpful to learn how the grammar format works. Thanks :+1: 

One more thing, what is your workflow to test changes in the grammar file with Atom?
