### ISSUE TITLE
Space after BEGIN or END {} blocks breaks syntax

### ISSUE THREAD

**Issue by ghost** [c-steiner/language-awk#7]
- syntax inside the { block } is broken in atom

``` awk
END {
    if (line || !fieldIndex) {
        exit !fieldIndex
    }
}
```
- ok in atom

``` awk
END{
    if (line || !fieldIndex) {
        exit !fieldIndex
    }
}
```

**Comment by c-steiner** [comment]
Can you give me more details? I can't see any difference:

![screenshot](https://cloud.githubusercontent.com/assets/15639707/12031627/946b5b24-ae0e-11e5-8081-2f987a99d8ba.png)

**Comment by ghost** [comment]
Must be the theme I was using. I will post a screenshot as soon as I have a chance for reference.

Thanks.

**Comment by ghost** [comment]
Seems to be a little glitch with Atom's Dark theme.

![untitled](https://cloud.githubusercontent.com/assets/8317250/12053056/9531d556-af58-11e5-8c14-2d6be4084bc6.png)
![untitled2](https://cloud.githubusercontent.com/assets/8317250/12053057/967240c2-af58-11e5-80a0-ce736a0ba9ae.png)

I switch themes fairly often and this is not a major problem for me TBH.

**Comment by c-steiner** [comment]
Thanks for the tipp. I've tested some other themes but Atom Dark was non of them. :smile: 

Fixed with the latest update.

**Comment by ghost** [comment]
:+1:
